# Generated by Django 4.1.3 on 2022-11-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caregory',
            new_name='Category',
        ),
    ]
