# Generated by Django 4.1.3 on 2022-11-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_rename_caregory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='one',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='one_point_five',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='point_five',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='three',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='twe_point_five',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='two',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
