# Generated by Django 4.1.3 on 2022-11-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_alter_category_one_alter_category_one_point_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
